---
spring:
  application:
    name: afs
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.18.33.147:3306/afs?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: l!vWT#mL93
#    filters: stat,wall,log4j
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200
#    redis
  redis:
    database: 0
    host: 172.18.33.147
    port: 6379
    password: pcpt
    timeout: 1000
    pool:
    jedis:
      pool:
        min-idle: 0
        max-idle: 200
        max-wait: -1

server:
  port: 8180
  servlet:
    context-path: /
    session:
      # cookie:
      #   http-only: true
      #   secure: true
      timeout: 30m
      persistent: false

mybatis:
  mapperLocations: classpath:mapping/*.xml
  typeAliasesPackage: com.thunisoft.model

# 自定义的jwt配置
jwt:
  # 过期时间：2分钟
  expire: 120000
  # 密钥
  secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52

## Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
